apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/kubereats/finance-service:dev
          imagePullPolicy: Always
