apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  APP_ENV: dev
  LOG_LEVEL: info
  SERVICE_NAME: notification-service
  EMAIL_PROVIDER: local
  SMTP_FROM_EMAIL: noreply@kubereats.local
  RATE_LIMIT_PER_MINUTE: "120"
