sonar.projectKey=kubereats-order-scheduler-service
sonar.projectName=KuberEats Order Scheduler Service
sonar.projectVersion=0.1.0

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=app,migrations
sonar.tests=tests,test
sonar.test.inclusions=tests/**/*.py,test/**/*.ts

sonar.exclusions=\
  **/__pycache__/**,\
  .venv/**,\
  .pytest_cache/**,\
  .ruff_cache/**,\
  node_modules/**
