apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubereats-dev
resources:
  - ../../../base/order-scheduler-service
patches:
  - path: patch-env.yaml
  - path: patch-replicas.yaml
  - path: patch-image.yaml
  - path: patch-service-nodeport.yaml
images:
  - name: ghcr.io/kubereats/order-scheduler-service
    newTag: 9640ba7
