apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-scheduler-service
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/kubereats/order-scheduler-service:dev
          imagePullPolicy: Always
