apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/kubereats/notification-service:TODO
          imagePullPolicy: Always
