ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS dietary_type VARCHAR(32) NOT NULL DEFAULT 'MEAT';

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS allergens JSONB NOT NULL DEFAULT '[]';

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS certifications JSONB NOT NULL DEFAULT '[]';

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS calories_kcal INTEGER;

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS protein_g NUMERIC(8,2);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS carbs_g NUMERIC(8,2);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS fat_g NUMERIC(8,2);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS sodium_mg NUMERIC(8,2);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS sugar_g NUMERIC(8,2);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS serving_size VARCHAR(50);

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS ingredients TEXT;
