ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS dietary_type VARCHAR(32) NOT NULL DEFAULT 'MEAT';

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS allergens JSONB NOT NULL DEFAULT '[]';

ALTER TABLE menu
    ADD COLUMN IF NOT EXISTS certifications JSONB NOT NULL DEFAULT '[]';
