apiVersion: v1
kind: ConfigMap
metadata:
  name: order-scheduler-service-config
data:
  APP_ENV: dev
  LOG_LEVEL: info
  SERVICE_NAME: order-scheduler-service
  QUEUE_BACKEND: fake
  DISPATCH_LEAD_MINUTES: "30"
  MAX_SCHEDULE_DAYS: "30"
  INTERNAL_TASK_AUTH_ENABLED: "false"
  INTERNAL_TASK_HANDLER_URL: http://order-scheduler-service/internal/tasks/orders/release
  GCP_PROJECT_ID: ""
  GCP_LOCATION: ""
  GCP_CLOUD_TASKS_QUEUE: ""
  GCP_TASK_HANDLER_URL: ""
  GCP_TASK_SERVICE_ACCOUNT_EMAIL: ""
