apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubereats-dev
resources:
  - ../../../base/order-consumer-service
patches:
  - path: patch-env.yaml
  - path: patch-replicas.yaml
  - path: patch-image.yaml
images:
  - name: ghcr.io/kubereats/order-consumer-service
    newTag: 43198f8
