apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubereats-dev
resources:
  - ../../../base/notification-service
patches:
  - path: patch-env.yaml
  - path: patch-replicas.yaml
  - path: patch-image.yaml
