apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: db-tools
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: dba@kubereats.internal
  PGADMIN_DEFAULT_PASSWORD: replace-with-generated-password
