apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubereats-monitoring
  namespace: argocd
spec:
  description: Kubereats cluster-local monitoring project
  sourceRepos:
    - https://github.com/KuberEats/kubereats-backend.git
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: kube-system
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
