apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubereats
  namespace: argocd
spec:
  description: Kubereats GitOps project
  sourceRepos:
    - https://github.com/KuberEats/kubereats-backend.git
    - https://github.com/KuberEats/kubereats-IaC.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kubereats-dev
    - server: https://kubernetes.default.svc
      namespace: kubereats-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: monitoring.coreos.com
      kind: PrometheusRule
