apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubereats-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:KuberEats/kubereats-backend.git
    targetRevision: main
    path: deploy/argocd/apps
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
