apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/kubereats/kubereats-verification:dev
          imagePullPolicy: Always
