apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubereats-prod
resources:
  - ../../base
images:
  - name: ghcr.io/kubereats/kubereats-verification
    newTag: prod
patches:
  - target:
      kind: ConfigMap
      name: verification-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
  - target:
      kind: Deployment
      name: verification
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
