apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubereats-db-patroni
  labels:
    app.kubernetes.io/name: patroni
    app.kubernetes.io/part-of: kubereats-monitoring
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: patroni
      component: postgres-ha
  targetLabels:
    - env
    - cluster
    - component
    - node
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubereats-db-postgres-exporter
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: kubereats-monitoring
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
      component: postgres-exporter
  targetLabels:
    - env
    - cluster
    - component
    - node
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubereats-db-node-exporter
  labels:
    app.kubernetes.io/name: db-node-exporter
    app.kubernetes.io/part-of: kubereats-monitoring
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: db-node-exporter
      component: db-node-exporter
  targetLabels:
    - env
    - cluster
    - component
    - node
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
