apiVersion: v1
kind: Secret
metadata:
  name: verification-service-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://TODO
  JWT_SECRET_KEY: TODO
  SMTP_USERNAME: TODO
  SMTP_PASSWORD: TODO
  MAILGUN_API_KEY: TODO
