apiVersion: v1
kind: Service
metadata:
  name: verification-service
  labels:
    app.kubernetes.io/name: verification-service
    app.kubernetes.io/part-of: kubereats
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: verification-service
    app.kubernetes.io/part-of: kubereats
  ports:
    - name: http
      port: 80
      targetPort: http
